# Generated by Django 4.1.2 on 2022-10-11 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(default=datetime.datetime(2022, 10, 11, 16, 46, 53, 955522))),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guides.carbrands', verbose_name='Марка')),
                ('color', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guides.colors', verbose_name='Цвет')),
                ('model', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guides.carmodels', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
